homogenize coding style

diff --git a/bin/genome-env-next b/bin/genome-env-next
--- a/bin/genome-env-next
+++ b/bin/genome-env-next
@@ -105,11 +105,13 @@ function main {
     log.info "Test DB Name: $TESTDBSERVER_DB_NAME"
     log.info ''
 
-    if [ $# -gt 0 ]; then
+    if test "$#" -gt 0
+    then
         log.info "$@"...
         exec "$@"
     else
-        if [ -n "$BASH" ]; then
+        if test -n "$BASH"
+        then
             echo 'Press <Ctrl>-D or type `logout` to return to normal environment.'
             echo ''
             if test -z "$GE_ENV_NAME"
@@ -294,7 +296,8 @@ function prepare_submodules {
 
         __quiet_git submodule sync "$@"
 
-        for submodule in "$@"; do
+        for submodule in "$@"
+        do
             log.info -n "   $submodule: "
             if git submodule status $submodule | grep -q ^-
             then
@@ -319,7 +322,7 @@ function prepare_submodules {
                         log.info "OK"
                     else
                         log.info "ERROR: submodule has local changes"
-                        exit 1;
+                        exit 1
                     fi
                 )
             fi
@@ -331,7 +334,8 @@ function regen_db {
     local DB_TXT="$1"
     log.info -n '.'
     DB_BIN=${DB_TXT/-dump/}
-    if [[ "$DB_BIN" -ot "$DB_TXT" ]]; then
+    if test "$DB_BIN" -ot "$DB_TXT"
+    then
         rm -f "$DB_BIN"
         sqlite3 "$DB_BIN" < "$DB_TXT"
     fi
@@ -431,8 +435,13 @@ function setup_env {
         fi
     done
 
-    for BIN in ur workflow genome; do
-        if which $BIN | grep -q "$SNAPSHOT_BIN"; then log.info "$BIN found in $SNAPSHOT_BIN! Aborting!" && exit 1; fi
+    for BIN in ur workflow genome
+    do
+        if which $BIN | grep -q "$SNAPSHOT_BIN"
+        then
+            log.info "$BIN found in $SNAPSHOT_BIN! Aborting!"
+            exit 1
+        fi
     done
 
     export GENOME_DS_GMSCHEMA_SERVER="dbname=${TESTDBSERVER_DB_NAME};host=${TESTDBSERVER_DB_HOST};port=${TESTDBSERVER_DB_PORT}"
