add 'fatal' function

diff --git a/bin/genome-env-next b/bin/genome-env-next
--- a/bin/genome-env-next
+++ b/bin/genome-env-next
@@ -103,8 +103,7 @@ function main {
             export PS1="(${GE_ENV_NAME}) \w $ "
             exec bash --norc --noprofile
         else
-            echo 'Only `bash` shells are supported at this time.'
-            exit 128
+            fatal 128 'Only `bash` shells are supported at this time.'
         fi
     fi
 }
@@ -145,13 +144,10 @@ function parse_opts {
                 WF_REPO="$OPTARG"
                 ;;
             :)
-                log.error "option -$OPTARG requires an argument"
-                exit 1
+                fatal 1 "option -$OPTARG requires an argument"
                 ;;
             \?)
-                log.error "illegal option -- $OPTARG"
-                usage
-                exit 1
+                fatal 1 "illegal option -- $OPTARG"
                 ;;
         esac
     done
@@ -163,34 +159,29 @@ function parse_opts {
 function validate_opts {
     if test -n "$DISABLE_DB" -a -n "$DISABLE_MIGRATIONS"
     then
-        log.error "cannot use -S and -M options together"
-        exit 2
+        fatal 2 "cannot use -S and -M options together"
     fi
 
     if test -n "$DISABLE_DB" -a -n "$SNAPSHOT_NAME"
     then
-        log.error "cannot use -S and -s options together"
-        exit 2
+        fatal 2 "cannot use -S and -s options together"
     fi
 
     if test -n "$DISABLE_UR" -a -n "$UR_REPO"
     then
-        log.error "cannot use -U and -u options together"
-        exit 2
+        fatal 2 "cannot use -U and -u options together"
     fi
 
     if test -n "$DISABLE_WF" -a -n "$WF_REPO"
     then
-        log.error "cannot use -W and -w options together"
-        exit 2
+        fatal 2 "cannot use -W and -w options together"
     fi
 
     if test -n "$SNAPSHOT_NAME"
     then
         if ! test-db template list | cut -f 1 | $GREP -q "^${SNAPSHOT_NAME}$"
         then
-            log.error "invalid snapshot name -- $SNAPSHOT_NAME"
-            exit 2
+            fatal 2 log.error "invalid snapshot name -- $SNAPSHOT_NAME"
         fi
     fi
 
@@ -208,8 +199,7 @@ function validate_opts {
 function assert_dir {
     if ! test -d "$2"
     then
-        log.error "$1 value must be a directory -- $2"
-        exit 2
+        fatal 2 "$1 value must be a directory -- $2"
     fi
 }
 
@@ -225,8 +215,7 @@ function set_defaults {
     then
         if test -z "$TOP" -o ! -d "$TOP/ur"
         then
-            log.error "-u must be specified if not in a Genome repo"
-            exit 2
+            fatal 2 "-u must be specified if not in a Genome repo"
         fi
         SUBMODULES=(ur)
         UR_REPO="$TOP/ur"
@@ -236,8 +225,7 @@ function set_defaults {
     then
         if test -z "$TOP" -o ! -d "$TOP/workflow"
         then
-            log.error "-w must be specified if not in a Genome repo"
-            exit 2
+            fatal 2 "-w must be specified if not in a Genome repo"
         fi
         SUBMODULES=("${SUBMODULES[@]}" workflow)
         WF_REPO="$TOP/workflow"
@@ -260,6 +248,13 @@ function __quiet_git {
             exit $GIT_EXIT
         fi
     )
+}
+
+function fatal {
+    EXIT="$1"
+    shift
+    log.error "$@"
+    exit $EXIT
 }
 
 function log.error {
@@ -302,8 +297,7 @@ function prepare_submodules {
                         __quiet_git submodule update --init $submodule
                         log.info "OK"
                     else
-                        log.info "ERROR: submodule has local changes"
-                        exit 1
+                        fatal 1 "submodule has local changes"
                     fi
                 )
             fi
@@ -351,8 +345,7 @@ function setup_test_db {
     eval "$(test-db database create --bash --owner $TESTDBSERVER_DB_USER --based-on $SNAPSHOT_NAME)"
     if test -z "$TESTDBSERVER_DB_NAME"
     then
-        log.info "Failed to create test database."
-        exit 1
+        fatal 1 "Failed to create test database."
     fi
 
     if test -z "$DISABLE_MIGRATIONS"
@@ -394,8 +387,7 @@ function setup_env {
     do
         if genome-perl -M$MODULE -e 1 2> /dev/null
         then
-            log.error "still found $MODULE after removing deployed snapshot"
-            exit 1
+            fatal "still found $MODULE after removing deployed snapshot"
         fi
     done
 
@@ -411,8 +403,7 @@ function setup_env {
     do
         if ! genome-perl -M$MODULE -e 1 2> /dev/null
         then
-            log.error "failed to load $MODULE"
-            exit 1
+            fatal 1 "failed to load $MODULE"
         fi
     done
 
@@ -420,8 +411,7 @@ function setup_env {
     do
         if which $BIN | $GREP -q "$SNAPSHOT_BIN"
         then
-            log.info "$BIN found in $SNAPSHOT_BIN! Aborting!"
-            exit 1
+            fatal 1 "$BIN found in $SNAPSHOT_BIN! Aborting!"
         fi
     done
 
@@ -434,10 +424,10 @@ function setup_env {
 
 THIS="$(basename "$0")"
 
-GIT="$(type -p git)" || ( log.error "git is required" && exit 1 )
-SQITCH="$(type -p sqitch)" || ( log.error "sqitch is required" && exit 1 )
-SQLITE3="$(type -p sqlite3)" || ( log.error "sqlite3 is required" && exit 1 )
-GREP="$(type -p grep)" || ( log.error "grep is required" && exit 1 )
+GIT="$(type -p git)" || fatal 1 "git is required"
+SQITCH="$(type -p sqitch)" || fatal 1 "sqitch is required"
+SQLITE3="$(type -p sqlite3)" || fatal 1 "sqlite3 is required"
+GREP="$(type -p grep)" || fatal 1 "grep is required"
 
 if test -z "$STOP_GENOME_ENV_REDIRECT"
 then
